### ISSUE TITLE
error line 92

### ISSUE THREAD

**Issue by shawngraham** [AllisonKuhl/hist4006-cluny-final-project#2]
Hi Allison,

Just gave it a go, got this error:

```
Shawns-MacBook-Pro-2:documents shawngraham$ python peasant.py
Welcome to Peasant Simulator.
It is time to plow your land. Press enter to plow your land. 
Traceback (most recent call last):
  File "peasant.py", line 292, in <module>
    main()  
  File "peasant.py", line 92, in main
    next = input("It is time to plow your land. Press enter to plow your land. ")
  File "<string>", line 0

    ^
SyntaxError: unexpected EOF while parsing
```

According to this: http://stackoverflow.com/questions/5074225/python-unexpected-eof-while-parsing you should be using `raw_input` instead of `input` in line 92. Which fixed it on my machine.

**Comment by shawngraham** [comment]
actually, I had to change `input` to `raw_input` in the other locations in the simulation, then it runs on my machine. This is very impressive Allison!

**Comment by AllisonKuhl** [comment]
when I use raw_input, it just gives me an error. :I  Maybe it's because you're using an earlier version of python?

**Comment by shawngraham** [comment]
ah, that's interesting. I've got 2.7.10 underway here. Should've put that in my issue. Are you using python 3?
