### ISSUE TITLE
'int' object has no attribute 'grow'

### ISSUE THREAD

**Issue by shawngraham** [AllisonKuhl/hist4006-cluny-final-project#3]
Hi Allison,

Things ticked along well, but then this happened:

```
('The weather today is:', 'rainy.')
The week passes unevenfully.
Your plants look pretty happy.
Traceback (most recent call last):
  File "peasant.py", line 292, in <module>
    main()  
  File "peasant.py", line 156, in main
    i.grow(weather, drought, rain) #we call the "grow function" that makes it grow
AttributeError: 'int' object has no attribute 'grow'
```

Some of the Stackoverflow people suggest that the problem is indentation, spaces vs tabs http://stackoverflow.com/questions/11685936/python-attributeerror-object-has-no-attribute

**Comment by AllisonKuhl** [comment]
Okay it should be working now!

**Comment by shawngraham** [comment]
cool!
